### ISSUE TITLE
Nomor bab

### ISSUE THREAD

**Issue by za** [ngoprek-kubernetes/examples#1]
Halo,

Bagaimana kalau nama file bagian nomor bab-nya diawali dengan 0? Untuk bab yang lebih kecil dari 10. Jadi bisa urut saat di-list nanti.

```
bab-07c-kudemo-api-deployment.yaml
...
bab-11b-kudemo-api-deployment.yaml
```

#minor

**Comment by za** [comment]
oh, belum ada PR-nya ternyata mas @girikuncoro . Klo issue-nya OK, nanti aku buatkan PR-nya.

**Comment by girikuncoro** [comment]
@za terimakasih, ide bagus ini, langsung bungkus, boleh minta tolong raise PR nya?
