### ISSUE TITLE
Tambahkan informasi pemesanan buku di README

### ISSUE THREAD

**Issue by za** [ngoprek-kubernetes/examples#4]
Halo @girikuncoro / @raffifu 

Bagaimana jika di `README` ditambahkan informasi untuk pemesanan buku via penerbit? Untuk memudahkan pembaca repo ini jika ingin membeli buku.

PS: Pencarian di lokapasar memunculkan hasil dengan harga yang berbeda-beda. Hihihi...

**Comment by girikuncoro** [comment]
terimakasih atas masukannya, untuk sarannya saya tambahkan informasi pemesanan buku yang ini cukup kah?

https://bit.ly/PO-Kubernetes

beserta dengan ebook di android playstore

saya pantau di tokopedia juga banyak tapi memang harganya tergantung resellernya https://www.tokopedia.com/search?st=&q=kubernetes%20pemula

**Comment by za** [comment]
Oh, ternyata di repo ini sudah ada informasi-nya mas @girikuncoro https://github.com/ngoprek-kubernetes/buku-kubernetes-pemula

Mungkin bisa ditambahkan saja tautan di atas di `README`. Bagaimana Mas Giri?

**Comment by girikuncoro** [comment]
ohya betul mas @ariscahyadi yang tambahkan waktu itu, sip begitu saja, boleh minta tolong raise PR? terimakasih

**Comment by ariscahyadi** [comment]
@za dan @girikuncoro saya sudah update pemesanan lewat pre-order, marketplace dan google play store disini https://github.com/ngoprek-kubernetes/buku-kubernetes-pemula

**Comment by za** [comment]
Saya sudah buat PR ya mas @girikuncoro cc: mas @ariscahyadi

**Comment by ariscahyadi** [comment]
Sudah di merge ya @za dan @girikuncoro

**Comment by za** [comment]
Sip mas @ariscahyadi
